USE [DB_SOF_01]
GO

/****** Object:  Table [dbo].[USER]    Script Date: 5/13/2019 10:51:30 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[USER](
	[ID_EMP] [nvarchar](10) NOT NULL,
	[NAME] [nvarchar](50) NOT NULL,
	[TYPE] [nvarchar](50) NOT NULL,
	[USERNAME] [nvarchar](50) NOT NULL,
	[PASSWORD] [nvarchar](10) NOT NULL,
	[DATESTART] [datetime2](7) NOT NULL,
	[ADDRESS] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_USER] PRIMARY KEY CLUSTERED 
(
	[ID_EMP] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[FOOD_CATEGORY]    Script Date: 5/13/2019 10:51:05 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[FOOD_CATEGORY](
	[ID_CAT] [nvarchar](10) NOT NULL,
	[NAMECAT] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_FOOD_CATEGORY] PRIMARY KEY CLUSTERED 
(
	[ID_CAT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[FOOD]    Script Date: 5/13/2019 10:50:49 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[FOOD](
	[ID_FOD] [nvarchar](10) NOT NULL,
	[ID_CAT] [nvarchar](10) NOT NULL,
	[DISPLAYNAME] [nvarchar](50) NOT NULL,
	[OUTPUTPRICE] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_FOOD] PRIMARY KEY CLUSTERED 
(
	[ID_FOD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


